/**************************************************************************/
/* Copyright (c) 2019 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           6851

#define PATCH_ENTRY_CREATE_MUTE_OP               0x04003fa5 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x04003fdf /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x04003fe5 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04004fcd /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x0400525d /* $_get_bt_address */
#define PATCH_ENTRY_SET_LIC_DEBUG                0x0400537d /* $_set_lic_debug */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
