/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from av_headset_db.db_
 */
#ifndef __AV_HEADSET_DB_H
#define __AV_HEADSET_DB_H

#include <csrtypes.h>

#define HANDLE_GATT_SERVICE             (0x0001)
#define HANDLE_GATT_SERVICE_END         (0x0004)
#define HANDLE_GATT_SERVICE_CHANGED     (0x0003)
#define HANDLE_GATT_SERVICE_CHANGED_CLIENT_CONFIG (0x0004)
#define HANDLE_GAP_SERVICE              (0x0005)
#define HANDLE_GAP_SERVICE_END          (0xffff)
#define HANDLE_DEVICE_NAME              (0x0007)
#define HANDLE_DEVICE_APPEARANCE        (0x0009)

typedef enum
{
    GAP_SERVICE,
    
    gatt_sdp_last
} gatt_sdp;

uint8 *GattGetServiceRecord(gatt_sdp service, uint16 *len);
uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
