/****************************************************************************
Generated from F:\Fang_WorkNotes\project\W1\SW\W1_V005_ADK630\apps\applications\earbud\qcc512x_qcc302x\QCC3020-AA_DEV-BRD-R2-AA\dfu\dfu-public.key
by C:\qtil\ADK_QCC512x_QCC302x_WIN_6.3.0.154\tools\gen_rsa_pss_constants.py
at 18:09:19 13/04/2019

FILE NAME
    rsa_pss_constants.c

DESCRIPTION
    Constant data needed for the rsa_decrypt and the ce_pkcs1_pss_padding_verify
    function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the CONFIG_HYDRACORE VM upgrade library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

****************************************************************************/

#include "rsa_decrypt.h"

/*
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
const rsa_mod_t rsa_decrypt_constant_mod = {
    /* uint16 M[RSA_SIGNATURE_SIZE] where RSA_SIGNATURE_SIZE is 128 */
    {
        0xe01a,     /* 00 */
        0x2f30,     /* 01 */
        0x4a0d,     /* 02 */
        0x6fe2,     /* 03 */
        0xa1a5,     /* 04 */
        0x3bb2,     /* 05 */
        0x6e64,     /* 06 */
        0x2d00,     /* 07 */
        0xcc3a,     /* 08 */
        0xbf10,     /* 09 */
        0x79cc,     /* 10 */
        0x56fd,     /* 11 */
        0x7729,     /* 12 */
        0xc872,     /* 13 */
        0x4b24,     /* 14 */
        0x2f61,     /* 15 */
        0xa913,     /* 16 */
        0x7ec1,     /* 17 */
        0x229c,     /* 18 */
        0xc812,     /* 19 */
        0xdb4c,     /* 20 */
        0xf61e,     /* 21 */
        0x8d65,     /* 22 */
        0x7cfe,     /* 23 */
        0x5409,     /* 24 */
        0x54b2,     /* 25 */
        0xcb40,     /* 26 */
        0xac88,     /* 27 */
        0x0047,     /* 28 */
        0x4b28,     /* 29 */
        0x7f7b,     /* 30 */
        0xcf89,     /* 31 */
        0x6978,     /* 32 */
        0x396b,     /* 33 */
        0x1d09,     /* 34 */
        0x2800,     /* 35 */
        0x3e72,     /* 36 */
        0x33bf,     /* 37 */
        0x900c,     /* 38 */
        0xebda,     /* 39 */
        0xe472,     /* 40 */
        0x987d,     /* 41 */
        0xb6d7,     /* 42 */
        0x35b9,     /* 43 */
        0x0d9b,     /* 44 */
        0x68c8,     /* 45 */
        0xe6fd,     /* 46 */
        0x15f2,     /* 47 */
        0x595e,     /* 48 */
        0xa85b,     /* 49 */
        0xb03d,     /* 50 */
        0x10ff,     /* 51 */
        0xaadf,     /* 52 */
        0xaa52,     /* 53 */
        0xcb47,     /* 54 */
        0xaa0a,     /* 55 */
        0xbdc5,     /* 56 */
        0xd1a4,     /* 57 */
        0x9087,     /* 58 */
        0xf19d,     /* 59 */
        0x86a0,     /* 60 */
        0x1ddc,     /* 61 */
        0xb02a,     /* 62 */
        0xf838,     /* 63 */
        0xd678,     /* 64 */
        0xbd32,     /* 65 */
        0xfd8d,     /* 66 */
        0x0798,     /* 67 */
        0xd83f,     /* 68 */
        0xa797,     /* 69 */
        0xc749,     /* 70 */
        0x7e60,     /* 71 */
        0x4774,     /* 72 */
        0x845d,     /* 73 */
        0x60f7,     /* 74 */
        0x23dd,     /* 75 */
        0x5bdd,     /* 76 */
        0xf45f,     /* 77 */
        0x2d5f,     /* 78 */
        0xd82b,     /* 79 */
        0xa0cd,     /* 80 */
        0xcce4,     /* 81 */
        0x7e48,     /* 82 */
        0x4783,     /* 83 */
        0x04a7,     /* 84 */
        0x0773,     /* 85 */
        0x37a1,     /* 86 */
        0x6874,     /* 87 */
        0x5edc,     /* 88 */
        0x759b,     /* 89 */
        0xc8bd,     /* 90 */
        0xd4de,     /* 91 */
        0xb5f8,     /* 92 */
        0xef54,     /* 93 */
        0x5c77,     /* 94 */
        0x7caa,     /* 95 */
        0xd815,     /* 96 */
        0xccc9,     /* 97 */
        0x8a4e,     /* 98 */
        0x4c84,     /* 99 */
        0x2076,     /* 100 */
        0x9e33,     /* 101 */
        0x88a9,     /* 102 */
        0xf9e0,     /* 103 */
        0x1de6,     /* 104 */
        0xcf19,     /* 105 */
        0x3e49,     /* 106 */
        0x9b5d,     /* 107 */
        0x995d,     /* 108 */
        0x6890,     /* 109 */
        0x2fe1,     /* 110 */
        0xe2e4,     /* 111 */
        0x8471,     /* 112 */
        0x7f46,     /* 113 */
        0x865d,     /* 114 */
        0x73f8,     /* 115 */
        0x2cfc,     /* 116 */
        0xf7ea,     /* 117 */
        0x0336,     /* 118 */
        0x6a39,     /* 119 */
        0x84e7,     /* 120 */
        0x06d2,     /* 121 */
        0xb019,     /* 122 */
        0xcfd1,     /* 123 */
        0x9e5b,     /* 124 */
        0xcc6e,     /* 125 */
        0xc162,     /* 126 */
        0x2233      /* 127 */
    },
    /* uint16 M_dash */
    0x5705
};

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE] = {
    0x9266,     /* 00 */
    0xae3a,     /* 01 */
    0xe96a,     /* 02 */
    0xcf43,     /* 03 */
    0x93ba,     /* 04 */
    0x98e7,     /* 05 */
    0x990a,     /* 06 */
    0xd4d2,     /* 07 */
    0x075d,     /* 08 */
    0x909b,     /* 09 */
    0x49be,     /* 10 */
    0x163f,     /* 11 */
    0x07e1,     /* 12 */
    0xc938,     /* 13 */
    0x95a1,     /* 14 */
    0x0071,     /* 15 */
    0x62f3,     /* 16 */
    0x9038,     /* 17 */
    0x8df0,     /* 18 */
    0x33c2,     /* 19 */
    0x34ff,     /* 20 */
    0x8c17,     /* 21 */
    0xb573,     /* 22 */
    0xdbf1,     /* 23 */
    0x9d97,     /* 24 */
    0x70e0,     /* 25 */
    0x5ecb,     /* 26 */
    0xd7e0,     /* 27 */
    0xbe7e,     /* 28 */
    0x74b4,     /* 29 */
    0xe14c,     /* 30 */
    0xb374,     /* 31 */
    0xd30d,     /* 32 */
    0x16f5,     /* 33 */
    0x906c,     /* 34 */
    0x3b19,     /* 35 */
    0x7947,     /* 36 */
    0x7a23,     /* 37 */
    0x65e8,     /* 38 */
    0x8468,     /* 39 */
    0xf927,     /* 40 */
    0xc6e8,     /* 41 */
    0x20e5,     /* 42 */
    0xd3ee,     /* 43 */
    0x4548,     /* 44 */
    0x2b48,     /* 45 */
    0xf9f9,     /* 46 */
    0x2bb1,     /* 47 */
    0x8f37,     /* 48 */
    0x98f8,     /* 49 */
    0xd22e,     /* 50 */
    0x0f7c,     /* 51 */
    0x9417,     /* 52 */
    0x4600,     /* 53 */
    0xbaeb,     /* 54 */
    0x8503,     /* 55 */
    0x38be,     /* 56 */
    0xf4ab,     /* 57 */
    0x6638,     /* 58 */
    0x80a8,     /* 59 */
    0x3825,     /* 60 */
    0x5aac,     /* 61 */
    0xb877,     /* 62 */
    0xf380,     /* 63 */
    0xba3a,     /* 64 */
    0x3eb1,     /* 65 */
    0x6360,     /* 66 */
    0x6e4b,     /* 67 */
    0x1cd8,     /* 68 */
    0xd55f,     /* 69 */
    0x55ca,     /* 70 */
    0xe4f3,     /* 71 */
    0xd008,     /* 72 */
    0x4821,     /* 73 */
    0xe978,     /* 74 */
    0x2604,     /* 75 */
    0xe2a5,     /* 76 */
    0x7dba,     /* 77 */
    0x77ab,     /* 78 */
    0x1137,     /* 79 */
    0x3657,     /* 80 */
    0xfe86,     /* 81 */
    0xa5e5,     /* 82 */
    0x5af9,     /* 83 */
    0x6156,     /* 84 */
    0x0b78,     /* 85 */
    0xd004,     /* 86 */
    0x2524,     /* 87 */
    0x8bf6,     /* 88 */
    0x5736,     /* 89 */
    0x5d35,     /* 90 */
    0x0da3,     /* 91 */
    0x8533,     /* 92 */
    0x94f8,     /* 93 */
    0x3049,     /* 94 */
    0x621d,     /* 95 */
    0xe142,     /* 96 */
    0x9b26,     /* 97 */
    0x0503,     /* 98 */
    0x46cc,     /* 99 */
    0x3b6e,     /* 100 */
    0x7ae5,     /* 101 */
    0x067e,     /* 102 */
    0x058d,     /* 103 */
    0xb5fc,     /* 104 */
    0x4faa,     /* 105 */
    0x0048,     /* 106 */
    0x967f,     /* 107 */
    0x3935,     /* 108 */
    0x7bc8,     /* 109 */
    0x8504,     /* 110 */
    0x8469,     /* 111 */
    0x84ea,     /* 112 */
    0x33b6,     /* 113 */
    0x8365,     /* 114 */
    0xc983,     /* 115 */
    0xeade,     /* 116 */
    0xa037,     /* 117 */
    0xf8e2,     /* 118 */
    0xb86f,     /* 119 */
    0xcc83,     /* 120 */
    0x79f5,     /* 121 */
    0x2d9d,     /* 122 */
    0xb7e2,     /* 123 */
    0x9d37,     /* 124 */
    0xc135,     /* 125 */
    0x69f9,     /* 126 */
    0x0498      /* 127 */
};

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen = 222;
