/* Copyright (c) 2016 Qualcomm Technologies International, Ltd. */
/*   Part of 6.3.0 */
/**
 * \file
 * Implementations of non-autogenerated operator-related trap calls
 */
#include "trap_api/trap_api_private.h"
#include <message.h>
#include <stream.h>
#include "ipc/ipc.h"

#if TRAPSET_OPERATOR

Source StreamSourceFromOperatorTerminal(Operator opid, uint16 terminal)
{
    /**
     * Formula from the Bluecore DSPManager Specification
     * http://cognidox/vdocs/CS-208512-SP-LATEST.pdf section 3.15
     */
    return SOURCE_FROM_ID((uint16)((uint16)opid + 0x2000 + terminal));
}

Sink StreamSinkFromOperatorTerminal(Operator opid, uint16 terminal)
{
    /**
     * Formula from the Bluecore DSPManager Specification
     * http://cognidox/vdocs/CS-208512-SP-LATEST.pdf section 3.15
     */
    return SINK_FROM_ID((uint16)((uint16)opid + 0xa000 + terminal));
}

Task MessageOperatorTask(Operator opid, Task task)
{
    /**
     * Operators and sinks are allocated from the same number space.
     * Therefore we can use the same mechanism for forwarding operator
     * messages as we do for sinks.
     */
    return MessageStreamTaskFromSink(SINK_FROM_ID(opid), task);
}

bool OperatorMessage(Operator opid,
                     const uint16 * send_msg, uint16 send_len_words,
                     uint16 * recv_msg, uint16 recv_len_words)
{
    IPC_OPERATOR_MESSAGE op_msg;
    IPC_OPERATOR_MESSAGE_RSP op_msg_rsp;

    op_msg.opid = opid;
    op_msg.send_msg = send_msg;
    op_msg.send_len_words = send_len_words;
    op_msg.recv_len_words = recv_msg ? recv_len_words : 0;
    ipc_send(IPC_SIGNAL_ID_OPERATOR_MESSAGE, &op_msg, sizeof(op_msg));
    (void)ipc_recv(IPC_SIGNAL_ID_OPERATOR_MESSAGE_RSP, &op_msg_rsp);

    if(recv_msg && recv_len_words)
    {
        memcpy(recv_msg, op_msg_rsp.recv_msg, recv_len_words * sizeof(uint16));
        pfree(op_msg_rsp.recv_msg);
    }
    return op_msg_rsp.ret;
}

bool OperatorFrameworkConfigurationGet(uint16 key,
        const uint16 * send_msg, uint16 send_len_words,
        uint16 * recv_msg, uint16 recv_len_words)
{
    IPC_OPERATOR_FRAMEWORK_CONFIGURATION_GET send_prim;
    IPC_OPERATOR_FRAMEWORK_CONFIGURATION_GET_RSP resp_prim;
    send_prim.key = key;
    send_prim.send_msg = send_msg;
    send_prim.send_len_words = send_len_words;
    send_prim.recv_len_words = recv_msg ? recv_len_words : 0;
    ipc_send(IPC_SIGNAL_ID_OPERATOR_FRAMEWORK_CONFIGURATION_GET, &send_prim, sizeof(send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_OPERATOR_FRAMEWORK_CONFIGURATION_GET_RSP, &resp_prim);

    if(recv_msg && recv_len_words)
    {
        memcpy(recv_msg, resp_prim.recv_msg, recv_len_words * sizeof(uint16));
        pfree(resp_prim.recv_msg);
    }
    return resp_prim.ret;
}

Task MessageOperatorFrameworkTask(Task task)
{
    return trap_api_register_message_task(task, IPC_MSG_TYPE_AUDIO);
}

#endif /* TRAPSET_OPERATOR */
