/**************************************************************************/
/* Copyright (c) 2018 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           5360

#define PATCH_ENTRY_CREATE_MUTE_OP               0x040040a1 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x040040db /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x040040e1 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04005303 /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x0400558f /* $_get_bt_address */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
