###########################################################
# Makefile generated by QMDE for CSRA68100                 
#                                                          
# Project: earbud
# Configuration: debug
# Generated: Mon 24. Jun 15:47:53 2019
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

BUILD_ID=E:\qtil\ADK_QCC512x_QCC302x_WIN_6.3.0.154\tools/ubuild/maker/buildid/examples/timestamp.py
BUILD_TYPE=DEBUG
CHIP_TYPE=qcc512x_qcc302x
DBG_CORE=app/p1
DEFAULT_LIBS=usb_early_init
DEFS=AV_DEBUG BLUELAB DEBUG HAVE_1_BUTTON HAVE_2_LEDS HAVE_32BIT_DATA_WIDTH HAVE_THERMISTORx HYDRA HYDRACORE INCLUDE_AV INCLUDE_CHARGER INCLUDE_DFU INCLUDE_GATT INCLUDE_HFP INCLUDE_MICFWD INCLUDE_PROMPTS INCLUDE_SCOFWD INCLUDE_TEMPERATUREx INCLUDE_TONES INSTALL_HYDRA_LOG QCC3020_AA_DEV_BRD_R2_AA THERMISTOR_ADC=adcsel_led5 THERMISTOR_DATA_FILE=thermistor_lp4549652p3m.h THERMISTOR_ON=THERMISTOR_PIO_UNUSED USE_BDADDR_FOR_LEFT_RIGHT __KALIMBA__ disCHAIN_MIC_SPK
EXTRA_WARNINGS=FALSE
FLASH_CONFIG=..\..\32Mbit_default_flash_config.py
HW_VARIANT=QCC3020-AA_DEV-BRD-R2-AA
IDE_CONFIG=debug
IDE_PROJECT=earbud
INCPATHS=../../../../installed_libs\include\firmware_qcc512x_qcc302x ../../../../installed_libs\include\firmware_qcc512x_qcc302x/app ../../../../installed_libs\include\profiles\default_qcc512x_qcc302x ../../../../installed_libs\include\standard ../../chains E:\qtil\ADK_QCC512x_QCC302x_WIN_6.3.0.154\audio/kalimba/kymera/common/interface/gen/k32
LIBPATHS=../../../../installed_libs\lib\default_qcc512x_qcc302x\native ../../../../installed_libs\lib\os\qcc512x_qcc302x
LIBS=a2dp audio_processor avrcp bdaddr byte_utils chain connection cryptovm custom_operator file_list gaia gatt gatt_gap_server gatt_manager gatt_server hfp input_event_manager operators packetiser_helper pio_common region rtime rwcp_server sdp_parse service system_clock upgrade vmal
OUTDIR=F:\Fang_WorkNotes\project\W1\SW\W1_V006\apps\applications\earbud\qcc512x_qcc302x\QCC3020-AA_DEV-BRD-R2-AA
OUTPUT=earbud
OUTPUT_TYPE=EXECUTABLE
PERCONFIGDEPEND=depend_debug_qcc512x_qcc302x
PRESERVED_LIBS=qcc512x_qcc302x
PRIVATE_DEFS=AURA
PRIVATE_INCPATHS=include/*.h
STRIP_SYMBOLS=FALSE


INPUTS=\
    ..\..\1_button.buttonxml \
    ..\..\av_headset_db.db \
    ..\..\av_headset_a2dp.c \
    ..\..\av_headset_auth.c \
    ..\..\av_headset_av.c \
    ..\..\av_headset_av_caps.c \
    ..\..\av_headset_av_remote.c \
    ..\..\av_headset_av_volume.c \
    ..\..\av_headset_avrcp.c \
    ..\..\av_headset_battery.c \
    ..\..\av_headset_charger.c \
    ..\..\av_headset_con_manager.c \
    ..\..\av_headset_config.c \
    ..\..\av_headset_conn_rules.c \
    ..\..\av_headset_device.c \
    ..\..\av_headset_gaia.c \
    ..\..\av_headset_gatt.c \
    ..\..\av_headset_handset_signalling.c \
    ..\..\av_headset_hfp.c \
    ..\..\av_headset_init.c \
    ..\..\av_headset_kymera.c \
    ..\..\av_headset_kymera_a2dp.c \
    ..\..\av_headset_kymera_common.c \
    ..\..\av_headset_kymera_mic_spk.c \
    ..\..\av_headset_kymera_sco.c \
    ..\..\av_headset_kymera_tones_prompts.c \
    ..\..\av_headset_led.c \
    ..\..\av_headset_link_policy.c \
    ..\..\av_headset_pairing.c \
    ..\..\av_headset_peer_signalling.c \
    ..\..\av_headset_peer_sync.c \
    ..\..\av_headset_phy_state.c \
    ..\..\av_headset_power.c \
    ..\..\av_headset_scan_manager.c \
    ..\..\av_headset_scofwd.c \
    ..\..\av_headset_sdp.c \
    ..\..\av_headset_sm.c \
    ..\..\av_headset_stubs.c \
    ..\..\av_headset_tasklist.c \
    ..\..\av_headset_temperature.c \
    ..\..\av_headset_test.c \
    ..\..\av_headset_ui.c \
    ..\..\av_headset_upgrade.c \
    ..\..\main.c \
    ..\..\peripherals\adxl362.c \
    ..\..\peripherals\thermistor.c \
    ..\..\peripherals\vncl3020.c \
    ..\..\chains\chain_aac_stereo_decoder_left.chain \
    ..\..\chains\chain_aac_stereo_decoder_right.chain \
    ..\..\chains\chain_aptx_mono_no_autosync_decoder.chain \
    ..\..\chains\chain_forwarding_input_aac_left.chain \
    ..\..\chains\chain_forwarding_input_aac_right.chain \
    ..\..\chains\chain_forwarding_input_aac_stereo_left.chain \
    ..\..\chains\chain_forwarding_input_aac_stereo_right.chain \
    ..\..\chains\chain_forwarding_input_aptx_left.chain \
    ..\..\chains\chain_forwarding_input_aptx_right.chain \
    ..\..\chains\chain_forwarding_input_sbc_left.chain \
    ..\..\chains\chain_forwarding_input_sbc_right.chain \
    ..\..\chains\chain_loopback.chain \
    ..\..\chains\chain_micfwd_nb.chain \
    ..\..\chains\chain_micfwd_nb_2mic.chain \
    ..\..\chains\chain_micfwd_send.chain \
    ..\..\chains\chain_micfwd_send_2mic.chain \
    ..\..\chains\chain_micfwd_wb.chain \
    ..\..\chains\chain_micfwd_wb_2mic.chain \
    ..\..\chains\chain_output_volume.chain \
    ..\..\chains\chain_prompt_decoder.chain \
    ..\..\chains\chain_prompt_decoder_no_iir.chain \
    ..\..\chains\chain_prompt_pcm.chain \
    ..\..\chains\chain_sbc_mono_no_autosync_decoder.chain \
    ..\..\chains\chain_sco_nb.chain \
    ..\..\chains\chain_sco_nb_2mic.chain \
    ..\..\chains\chain_sco_wb.chain \
    ..\..\chains\chain_sco_wb_2mic.chain \
    ..\..\chains\chain_scofwd_nb.chain \
    ..\..\chains\chain_scofwd_nb_2mic.chain \
    ..\..\chains\chain_scofwd_recv.chain \
    ..\..\chains\chain_scofwd_recv_2mic.chain \
    ..\..\chains\chain_scofwd_wb.chain \
    ..\..\chains\chain_scofwd_wb_2mic.chain \
    ..\..\chains\chain_tone_gen.chain \
    ..\..\chains\chain_tone_gen_no_iir.chain \
    ..\..\av_headset.h \
    ..\..\av_headset_a2dp.h \
    ..\..\av_headset_accelerometer.h \
    ..\..\av_headset_auth.h \
    ..\..\av_headset_av.h \
    ..\..\av_headset_avrcp.h \
    ..\..\av_headset_battery.h \
    ..\..\av_headset_chain_roles.h \
    ..\..\av_headset_charger.h \
    ..\..\av_headset_con_manager.h \
    ..\..\av_headset_config.h \
    ..\..\av_headset_conn_rules.h \
    ..\..\av_headset_device.h \
    ..\..\av_headset_gaia.h \
    ..\..\av_headset_gatt.h \
    ..\..\av_headset_handset_signalling.h \
    ..\..\av_headset_hfp.h \
    ..\..\av_headset_init.h \
    ..\..\av_headset_kymera.h \
    ..\..\av_headset_kymera_private.h \
    ..\..\av_headset_latency.h \
    ..\..\av_headset_led.h \
    ..\..\av_headset_link_policy.h \
    ..\..\av_headset_log.h \
    ..\..\av_headset_message.h \
    ..\..\av_headset_pairing.h \
    ..\..\av_headset_peer_signalling.h \
    ..\..\av_headset_peer_sync.h \
    ..\..\av_headset_phy_state.h \
    ..\..\av_headset_power.h \
    ..\..\av_headset_proximity.h \
    ..\..\av_headset_role.h \
    ..\..\av_headset_scan_manager.h \
    ..\..\av_headset_scofwd.h \
    ..\..\av_headset_sdp.h \
    ..\..\av_headset_sm.h \
    ..\..\av_headset_sm_private.h \
    ..\..\av_headset_tasklist.h \
    ..\..\av_headset_temperature.h \
    ..\..\av_headset_temperature_sensor.h \
    ..\..\av_headset_test.h \
    ..\..\av_headset_ui.h \
    ..\..\av_headset_upgrade.h \
    ..\..\peripherals\adxl362.h \
    ..\..\peripherals\thermistor.h \
    ..\..\peripherals\thermistor_lp4549652p3m.h \
    ..\..\peripherals\thermistor_ncp15xh103.h \
    ..\..\peripherals\vncl3020.h \
    build_id_str.c \
$(DBS)

-include earbud.mak
# Check required variables have been defined
ifdef MAKEFILE_RULES_DIR
  $(info Using $(MAKEFILE_RULES_DIR)/Makefile.rules)
  include $(MAKEFILE_RULES_DIR)/Makefile.rules
else
  ifdef SDK
    include $(SDK)/Makefile.rules
  else
    $(error Variable SDK has not been defined. It should be set to the location of the Devkit tools folder.)
  endif
endif
