/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_loopback.h
    \brief The chain_loopback chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_LOOPBACK_H__
#define _CHAIN_LOOPBACK_H__

/*!
    @startuml
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_VOLUME_CONTROL
        OPR_VOLUME_CONTROL : id = CAP_ID_VOL_CTRL_VOL
        OPR_VOLUME_CONTROL "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
        object EPR_SCO_MIC1 #lightgreen
        OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SCO_MIC1
        object EPR_SOURCE_MIXER_OUT #lightblue
        EPR_SOURCE_MIXER_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_loopback_config;

#endif /* _CHAIN_LOOPBACK_H__ */

