/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_loopback.c
    \brief The chain_loopback chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#include <chain_loopback.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../av_headset_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_BASIC_PASS, OPR_LATENCY_BUFFER),
    MAKE_OPERATOR_CONFIG(CAP_ID_VOL_CTRL_VOL, OPR_VOLUME_CONTROL)
};

static const operator_endpoint_t inputs[] =
{
    {OPR_LATENCY_BUFFER, EPR_SCO_MIC1, 0}
};

static const operator_endpoint_t outputs[] =
{
    {OPR_VOLUME_CONTROL, EPR_SOURCE_MIXER_OUT, 0}
};

static const operator_connection_t connections[] =
{
    {OPR_LATENCY_BUFFER, 0, OPR_VOLUME_CONTROL, 0, 1}
};

const chain_config_t chain_loopback_config = {0, 0, operators, 2, inputs, 1, outputs, 1, connections, 1};

