/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_micfwd_send.h
    \brief The chain_micfwd_send chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_MICFWD_SEND_H__
#define _CHAIN_MICFWD_SEND_H__

/*!
    @startuml
        object OPR_SCOFWD_RECV
        OPR_SCOFWD_RECV : id = CAP_ID_DOWNLOAD_ASYNC_WBS_DEC
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_VOLUME_CONTROL
        OPR_VOLUME_CONTROL : id = CAP_ID_VOL_CTRL_VOL
        object OPR_SCO_AEC
        OPR_SCO_AEC : id = CAP_ID_DOWNLOAD_AEC_REFERENCE
        object OPR_CVC_SEND
        OPR_CVC_SEND : id = CAP_ID_CVCHS1MIC_SEND_WB
        object OPR_MICFWD_SEND
        OPR_MICFWD_SEND : id = CAP_ID_DOWNLOAD_ASYNC_WBS_ENC
        object OPR_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SWITCHED_PASSTHROUGH_CONSUMER : id = CAP_ID_DOWNLOAD_SWITCHED_PASSTHROUGH_CONSUMER
        OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_SCOFWD_RECV
        OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
        OPR_SCO_AEC "INPUT1(0)"<-- "OUT(0)" OPR_VOLUME_CONTROL
        OPR_CVC_SEND "IN1(1)"<-- "OUTPUT1(3)" OPR_SCO_AEC
        OPR_CVC_SEND "REFERENCE(0)"<-- "REFERENCE(0)" OPR_SCO_AEC
        OPR_MICFWD_SEND "IN(0)"<-- "OUT(0)" OPR_CVC_SEND
        OPR_SWITCHED_PASSTHROUGH_CONSUMER "IN(0)"<-- "OUT(0)" OPR_MICFWD_SEND
        object EPR_SCOFWD_RX_OTA #lightgreen
        OPR_SCOFWD_RECV "FORWARDED_AUDIO(0)" <-- EPR_SCOFWD_RX_OTA
        object EPR_SCO_MIC1 #lightgreen
        OPR_SCO_AEC "MIC1(2)" <-- EPR_SCO_MIC1
        object EPR_VOLUME_AUX #lightgreen
        OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_VOLUME_AUX
        object EPR_SCO_SPEAKER #lightblue
        EPR_SCO_SPEAKER <-- "SPEAKER1(1)" OPR_SCO_AEC
        object EPR_MICFWD_TX_OTA #lightblue
        EPR_MICFWD_TX_OTA <-- "FORWARD(0)" OPR_SWITCHED_PASSTHROUGH_CONSUMER
    @enduml
*/

#include <chain.h>

extern const chain_config_t chain_micfwd_send_config;

#endif /* _CHAIN_MICFWD_SEND_H__ */

