/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_micfwd_send.c
    \brief The chain_micfwd_send chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#include <chain_micfwd_send.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../av_headset_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_ASYNC_WBS_DEC, OPR_SCOFWD_RECV),
    MAKE_OPERATOR_CONFIG(CAP_ID_SOURCE_SYNC, OPR_SOURCE_SYNC),
    MAKE_OPERATOR_CONFIG(CAP_ID_VOL_CTRL_VOL, OPR_VOLUME_CONTROL),
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_AEC_REFERENCE, OPR_SCO_AEC),
    MAKE_OPERATOR_CONFIG(CAP_ID_CVCHS1MIC_SEND_WB, OPR_CVC_SEND),
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_ASYNC_WBS_ENC, OPR_MICFWD_SEND),
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_SWITCHED_PASSTHROUGH_CONSUMER, OPR_SWITCHED_PASSTHROUGH_CONSUMER)
};

static const operator_endpoint_t inputs[] =
{
    {OPR_SCOFWD_RECV, EPR_SCOFWD_RX_OTA, 0},
    {OPR_SCO_AEC, EPR_SCO_MIC1, 2},
    {OPR_VOLUME_CONTROL, EPR_VOLUME_AUX, 1}
};

static const operator_endpoint_t outputs[] =
{
    {OPR_SCO_AEC, EPR_SCO_SPEAKER, 1},
    {OPR_SWITCHED_PASSTHROUGH_CONSUMER, EPR_MICFWD_TX_OTA, 0}
};

static const operator_connection_t connections[] =
{
    {OPR_SCOFWD_RECV, 0, OPR_SOURCE_SYNC, 0, 1},
    {OPR_SOURCE_SYNC, 0, OPR_VOLUME_CONTROL, 0, 1},
    {OPR_VOLUME_CONTROL, 0, OPR_SCO_AEC, 0, 1},
    {OPR_SCO_AEC, 3, OPR_CVC_SEND, 1, 1},
    {OPR_SCO_AEC, 0, OPR_CVC_SEND, 0, 1},
    {OPR_CVC_SEND, 0, OPR_MICFWD_SEND, 0, 1},
    {OPR_MICFWD_SEND, 0, OPR_SWITCHED_PASSTHROUGH_CONSUMER, 0, 1}
};

const chain_config_t chain_micfwd_send_config = {1, 0, operators, 7, inputs, 3, outputs, 2, connections, 7};

