/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_scofwd_recv_2mic.c
    \brief The chain_scofwd_recv_2mic chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#include <chain_scofwd_recv_2mic.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../av_headset_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_ASYNC_WBS_DEC, OPR_SCOFWD_RECV),
    MAKE_OPERATOR_CONFIG(CAP_ID_SOURCE_SYNC, OPR_SOURCE_SYNC),
    MAKE_OPERATOR_CONFIG(CAP_ID_VOL_CTRL_VOL, OPR_VOLUME_CONTROL),
    MAKE_OPERATOR_CONFIG(CAP_ID_DOWNLOAD_AEC_REFERENCE, OPR_SCO_AEC)
};

static const operator_endpoint_t inputs[] =
{
    {OPR_SCOFWD_RECV, EPR_SCOFWD_RX_OTA, 0},
    {OPR_SCO_AEC, EPR_SCO_MIC1, 2},
    {OPR_SCO_AEC, EPR_SCO_MIC2, 3},
    {OPR_VOLUME_CONTROL, EPR_VOLUME_AUX, 1}
};

static const operator_endpoint_t outputs[] =
{
    {OPR_SCO_AEC, EPR_SCO_SPEAKER, 1}
};

static const operator_connection_t connections[] =
{
    {OPR_SCOFWD_RECV, 0, OPR_SOURCE_SYNC, 0, 1},
    {OPR_SOURCE_SYNC, 0, OPR_VOLUME_CONTROL, 0, 1},
    {OPR_VOLUME_CONTROL, 0, OPR_SCO_AEC, 0, 1}
};

const chain_config_t chain_scofwd_recv_2mic_config = {1, 0, operators, 4, inputs, 4, outputs, 1, connections, 3};

