/*!
    \copyright Copyright (c) 2019 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.3.0
    \file chain_tone_gen.c
    \brief The chain_tone_gen chain. This file is generated by E:/qtil/ADK_QCC512x_QCC302x_WIN_6.3.0.154/tools/chaingen/chaingen.py.
*/

#include <chain_tone_gen.h>
#include <cap_id_prim.h>
#include <opmsg_prim.h>
#include <hydra_macros.h>
#include <../av_headset_chain_roles.h>
static const operator_config_t operators[] =
{
    MAKE_OPERATOR_CONFIG(CAP_ID_RINGTONE_GENERATOR, OPR_TONE_GEN),
    MAKE_OPERATOR_CONFIG(CAP_ID_IIR_RESAMPLER, OPR_TONE_PROMPT_RESAMPLER)
};

static const operator_endpoint_t outputs[] =
{
    {OPR_TONE_PROMPT_RESAMPLER, EPR_TONE_PROMPT_CHAIN_OUT, 0}
};

static const operator_connection_t connections[] =
{
    {OPR_TONE_GEN, 0, OPR_TONE_PROMPT_RESAMPLER, 0, 1}
};

const chain_config_t chain_tone_gen_config = {0, 0, operators, 2, NULL, 0, outputs, 1, connections, 1};

